sudo: required
branches:
  only:
  - ERC1484-dev
language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
before_install:
  - cd snowflake
install: npm install
before_script:
  - npm run chain > /dev/null &
  - sleep 5
  - npm run build
script: npm run test
