sudo: required
branches:
  only:
  - master
language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
install: npm install
before_script:
  - npm run chain > /dev/null & npm run chain-cover > /dev/null &
  - sleep 5
script: npm run test
after_script:
  - npm run cover && cat coverage/lcov.info | npx coveralls
